version: '3'

services:
  nextjs:
    build: .
    container_name: my_node_container
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development

volumes:
  node_modules:
  next: